### ISSUE TITLE
Use .. note:: to create note 

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig-docs-dev#1]
I see few notes currently in the documentation and suggest them to be displayed like as the image below using the
**.. note::**

![screenshot_2019-01-07 use notes and warnings rst sphinx sublime github documentation](https://user-images.githubusercontent.com/37617951/50784857-eb350d00-12d4-11e9-9e5e-11f5cef674ac.png)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Great idea!
