### ISSUE TITLE
Warning while installing virtualenv

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig-docs-dev#13]
Well I know why I am getting the following warning 
```
Warning: Your Pipfile requires python_version 3.5, but you are using 3.6.7 (/home/a/.local/share/v/s/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
```
I think as we are using **$ pipenv install --three**
this will by default make virtual environment with python3.x
and pipfile.lock can take care of everything else

**Comment by morevnaproject** [comment]
I wonder, if we can increase version in Pipfile.lock to python 3.6?

See also - http://blog.readthedocs.com/python-36-support/

**Comment by ankit-kumar-dwivedi** [comment]
> I wonder, if we can increase version in Pipfile.lock to python 3.6?
> 
> See also - http://blog.readthedocs.com/python-36-support/
In that case we should let it be how it is.

**Comment by ice0** [comment]
I think this will be enough: https://github.com/synfig/synfig-docs-dev/commit/b97221ee9a8f4e7511efa9e9e0aeb88a5294ecef

**Comment by morevnaproject** [comment]
Yay!
