### ISSUE TITLE
Add documentation for vectorization feature

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig-docs-dev#30]

**Comment by harshagrwl** [comment]
I'll be taking up this issue

**Comment by harshagrwl** [comment]
@ankit-kumar-dwivedi Please review #31

**Comment by morevnaproject** [comment]
Hmmm... I think this is better to add into user documentation (this repository is for developer documentation).

I think it is good idea to set up separate repository, which will hold user documentation in ReadTheDocs format. This is going to be a good replacement for Synfig MediaWiki documentation.

For example, see user documentation for OpenToonz - https://opentoonz.readthedocs.io/en/latest/

@ice0 @rodolforg

**Comment by harshagrwl** [comment]
@morevnaproject It is completely fine to add this to user documentation. But I think that only adding the vectorization feature in separate documentation will not make it complete. If we are setting up a completely new repository, we should add all the features as well as tutorials similar to OpenToonz documentation - https://opentoonz.readthedocs.io/en/latest/
@ankit-kumar-dwivedi @ice0

**Comment by ice0** [comment]
I support this!

**Comment by ankit-kumar-dwivedi** [comment]
+1 from my side

**Comment by morevnaproject** [comment]
Hi guys! My sincere apologies for delay, I will setup a separate repository for user docs tomorrow.

**Comment by morevnaproject** [comment]
Merged via https://github.com/synfig/synfig-docs/pull/1
