### ISSUE TITLE
Documentation builds for PRs

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig-docs-dev#34]
I came across this: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html
Can this be integrated to the documentation?

**Comment by AnishGG** [comment]
@morevnaproject could you have a look at this. ^__^

**Comment by ice0** [comment]
I will take a look

**Comment by AnishGG** [comment]
Great!

**Comment by ice0** [comment]
Done :) Need to check that feature.

**Comment by AnishGG** [comment]
> Done :) Need to check that feature.

Amazing!
So this P.R. build will be triggered on a new build? I will just create a new PR just to check this feature :P

**Comment by AnishGG** [comment]
@ice0 works perfectly!
