### ISSUE TITLE
Add code of conduct and contribution guidelines

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig-docs-dev#5]
There should be a code of conduct as I saw on any other open source org. So it will be easy for newcomers to know what they should follow and what they should not 😀

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject if you want I can create an initial draft.

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi That would help a lot! ^__^

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject working on it :+1:

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject I am facing a weird issue on GitHub 
though the PR is merged still it is showing that my fork is 4 commits ahead
PS: while looking at the previous PR I found there are 2 redundant commits
PPS: I have created the draft as I am unable to figure out why the error above is happening I didn't committed it yet

**Comment by ankit-kumar-dwivedi** [comment]
@morevnaproject Added initial draft :smiley:

**Comment by morevnaproject** [comment]
Thank you! I am reviewing it now. ^__^
