### ISSUE TITLE
Can't build with CMake 

### ISSUE THREAD

**Issue by rodolforg** [synfig/synfig-docs-dev#56]
By following the building instructions for CMake on Linux, I got nothing in the proposed "cmake-build" folder after run `cmake ..`.

**Comment by ice0** [comment]
Ok, I will take a look.

**Comment by ice0** [comment]
@rodolforg can you show your output after `cmake ..`?

**Comment by rodolforg** [comment]
It runs without error if I recall correctly.
But directory stay empty.
So I can't  `make`.

**Comment by AYESDIE** [comment]
Is this issue still up?

Maybe the output after using `cmake ..` can help it out. Because otherwise, I can't reproduce it as it works fine on my system (Ubuntu 20.04.1)

**Comment by ice0** [comment]
I think yes. @rodolforg is currently busy at work right now, so I think we can back to this issue when he have more time.

**Comment by rodolforg** [comment]
Ok. I followed again the same steps described in the docs… And it worked this time ;)
Thank you and congrats.
