### ISSUE TITLE
Qt Creator IDE set-up guide for synfig

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig-docs-dev#57]
Qt Creator supports CMake out of the box. It'd be nice if a new page about it is maintained on the doc page.

Maybe break the IDE page into two parts
- Setting up your preferred IDE for Synfig development
    - Netbeans
    - Qt Creator

One could create their own custom kit for Synfig in case they want to modify the CMake generator from the default one provided by Qt Creator (on Linux it's Unix Makefiles).

**Comment by ice0** [comment]
Agree.

**Comment by Keyikedalube** [comment]
Maybe I could do a draft document and PR here?
