### ISSUE TITLE
Reorder title contents

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig-docs-dev#65]
1. [x] After the user sets up his IDE, he should be guided directly to **Code structure**
Building Synfig and Dependencies are redundant because his IDE already takes care of that

2. [x] Shouldn't **Contributing guidelines** be on top?
Because this topic doesn't really have a chronological connection with previous and next. It's standalone just like Code of Conduct

3. [x] Group **Building Synfig** (<- rename it to Autotools) and **Synfig Using CMake** together
Just like NetBeans and QtCreator are grouped together under a single IDE topic

4. [x] Merge Preparing Environment sub-topic from Autotools and CMake together in one single section under **Building Synfig** category

5. [x] Move Package using CMake sub-topic from **Synfig Using CMake** to **Packaging Synfig for distribution**

![Screenshot from 2020-09-12 10-47-16](https://user-images.githubusercontent.com/24214509/92988086-17f7e980-f4e6-11ea-9a68-4659a3eb9b5d.png)

So here's an outline of how I think the new ordering should be:

```
   - Contributing guidelines
   - Setting up your preferred IDE
   - Code structure
   - Building synfig
      > Preparing environment
      > Autotools
      > CMake
   - Packaging synfig
      > Autotools
      > CMake
   - Tutorials
   ...
```

**Comment by ice0** [comment]
Agree.

**Comment by Keyikedalube** [comment]
Thanks, @ice0! Love your support ;)

**Comment by Keyikedalube** [comment]
If anyone wants to take on this issue, look at PR #64 - How I implemented a topic into subtopics (separate pages)

Same pattern can be used for breaking **Building Synfig** and **Packaging Synfig** into two sub-topics; Autotools and CMake.

**Comment by Keyikedalube** [comment]
@ice0 this is an easy issue too. Just reorganization needed.
👉 Hacktoberfest and easy 😁

**Comment by ice0** [comment]
@Keyikedalube Done!

**Comment by AYESDIE** [comment]
The *Preparing Environment* part for building with Autotools and CMake is the same. So if we are going that way, that information can be merged.

**Comment by Keyikedalube** [comment]
I guess you mean something like this:
```
- Building synfig
      > Preparing environment
      > Autotools
      > CMake
```

**Comment by AYESDIE** [comment]
Yep, I mean something like this. Because both of those *preparing environment* parts go over the installation of dependencies using the script that we have given and it's the same for Autotools and CMake.

**Comment by Keyikedalube** [comment]
I'll make a PR for this this evening.
