### ISSUE TITLE
Incomplete line

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [synfig/synfig-docs-dev#7]
@morevnaproject It seems like the ending word in [building doc](https://github.com/synfig/synfig-docs-dev/blob/master/docs/common/building.rst) line 213 is incomplete

> Let's suppose you made changes in synfig-studio and want to rebuild it without re

**Comment by morevnaproject** [comment]
Oh, thanks for pointing on this! This got lost somehow. ^__^
