### ISSUE TITLE
Typo in the idea list page of synfig !

### ISSUE THREAD

**Issue by DhairyaBahl** [synfig/synfig-docs-dev#72]
![Screenshot](https://user-images.githubusercontent.com/71627983/111600558-8a2fea80-87f7-11eb-91ea-45f5ec6a9e4f.png)

### Description 
Typo is, there is a  ```*```  after the skills required.

### Fix
If this is really an issue, then Kindly assign this to me ! I will fix this asap. Thanks :)

**Comment by ice0** [comment]
Done :)
